export const categories = [
    { slug: 'humanoid-robots', name: 'Humanoid Robots', tag: 'ADAPTIVE MANIPULATION', description: 'Human-scale platforms for supervised manipulation, research and repeatable workflows.', uses: ['Material handling trials', 'AI research and development', 'Controlled industrial pilots'], requirements: 'Validate payload, runtime, task repeatability and human–robot safety before deployment.' },
    { slug: 'quadruped-robots', name: 'Quadruped Robots', tag: 'MOBILE INSPECTION', description: 'Legged mobility for sensing and inspection across complex facilities.', uses: ['Thermal inspection', 'Remote facility rounds', 'Asset condition monitoring'], requirements: 'Assess terrain, ingress protection, communications and any hazardous-area certification.' },
    { slug: 'amr-logistics', name: 'AMR & Logistics', tag: 'INTELLIGENT MOVEMENT', description: 'Autonomous material movement connecting people, inventory and production.', uses: ['Warehouse transport', 'Line-side replenishment', 'Intralogistics'], requirements: 'Map traffic, fleet orchestration, load interfaces and emergency access.' },
    { slug: 'industrial-cobots', name: 'Industrial Robots & Cobots', tag: 'PRECISION AUTOMATION', description: 'Task-specific manipulation for production, assembly and material processing.', uses: ['Machine tending', 'Palletizing', 'Assembly assistance'], requirements: 'Engineer tooling, safeguarding and a task-specific risk assessment.' },
    { slug: 'cleaning-robots', name: 'Cleaning Robots', tag: 'FACILITY PRODUCTIVITY', description: 'Repeatable floor care with planned coverage and measurable service delivery.', uses: ['Terminal cleaning', 'Warehouse floor care', 'Hospitality facilities'], requirements: 'Confirm surface compatibility, water management, traffic patterns and hygiene protocols.' },
    { slug: 'service-delivery', name: 'Service & Delivery Robots', tag: 'CONNECTED SERVICE', description: 'Indoor delivery and assistance designed around the guest and staff journey.', uses: ['Hospitality delivery', 'Internal courier routes', 'Visitor assistance'], requirements: 'Validate lift integration, accessible circulation and safe handoff points.' },
    { slug: 'security-inspection', name: 'Security & Inspection Robots', tag: 'OPERATIONAL VISIBILITY', description: 'Mobile sensing to support inspection teams and facility awareness.', uses: ['Perimeter rounds', 'Remote visual inspection', 'Anomaly triage'], requirements: 'Review privacy, sensor permissions, escalation procedures and operator supervision.' },
] as const;
export const industries = [
    ['AI Data Centers', 'Thermal resilience, inspection and coordinated facility operations.'], ['Oil & Gas', 'Remote sensing and inspection workflows, subject to site and certification requirements.'], ['Logistics', 'Material movement, inventory visibility and predictable throughput.'], ['Manufacturing', 'Machine tending, handling and repeatable production tasks.'], ['Airports', 'Cleaning, delivery and inspection around passenger operations.'], ['Hospitality', 'Service delivery and facility care that support staff.'], ['Construction', 'Site sensing and progress visibility in evolving environments.'], ['Healthcare', 'Internal logistics and facility support under clinical safety protocols.'],
] as const;
export const models = [
    ['Buy', 'Own the capability.', 'Capital purchase for defined, long-term workflows. Scope integration, training, support and spares separately.'],
    ['Lease', 'Plan your investment.', 'Structured access over an agreed term, subject to credit approval, territory and equipment availability.'],
    ['Rent', 'Prove the use case.', 'Time-bound access for demonstrations, trials and temporary requirements, subject to availability.'],
    ['RaaS', 'Focus on the operation.', 'A scoped service combining equipment, deployment and support against agreed operating responsibilities and service measures.'],
] as const;
export const pages = {
    robotics: { eyebrow: 'ROBOTICS & PHYSICAL AI', title: 'Intelligence, put to work.', description: 'Turn physical AI into a practical operating capability. Start with the task, validate the environment, then select the platform and commercial model.' },
    'liquid-cooling': { eyebrow: 'AI INFRASTRUCTURE', title: 'Built for the heat of AI.', description: 'Plan high-density compute around the infrastructure it needs: liquid cooling, thermal visibility and serviceable system design.' },
    industries: { eyebrow: 'INDUSTRIES', title: 'Designed around your environment.', description: 'Every facility has different constraints. We align technology with your workflows, safety requirements and operational objectives.' },
    raas: { eyebrow: 'ROBOTICS-AS-A-SERVICE', title: 'From equipment to outcomes.', description: 'Build a service around a measurable task. Define coverage, availability, operator responsibilities and support before choosing a commercial structure.' },
    'technology-partners': { eyebrow: 'TECHNOLOGY ECOSYSTEM', title: 'Build what comes next. Together.', description: 'We welcome discussions with robotics manufacturers, cooling specialists, sensor providers and software teams that share a practical approach to deployment.' },
    company: { eyebrow: 'AERVYNT AI', title: 'The physical foundation of intelligence.', description: 'AERVYNT AI brings AI infrastructure, robotics and autonomous operations into one engineering-led conversation.' },
    'autonomous-data-center-operations': { eyebrow: 'CONNECTED OPERATIONS', title: 'One facility. A shared operational picture.', description: 'A reference architecture connecting liquid cooling, fixed sensors, mobile robotics and AI monitoring—supported by a digital twin and human oversight.' },
} as const;
export type PageSlug = keyof typeof pages;
