import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { pages, categories, industries, models, type PageSlug } from '@/lib/content';
import { Button, CTA, SectionHeading } from '@/components/ui';
import { InfraVisual } from '@/components/infra-visual';
export function generateStaticParams() { return Object.keys(pages).map(slug => ({ slug })); }
export async function generateMetadata({ params }: {
    params: Promise<{
        slug: string;
    }>;
}): Promise<Metadata> { const { slug } = await params; const page = pages[slug as PageSlug]; if (!page)
    return {}; return { title: page.eyebrow, description: page.description, alternates: { canonical: `/${slug}` }, openGraph: { title: page.title, description: page.description, url: `/${slug}` } }; }
const cooling = [['Direct-to-chip cooling', 'Assess cold plate interfaces, coolant compatibility, heat load and serviceability.'], ['Cooling distribution', 'Plan CDU sizing, hydraulic boundaries, redundancy and facility integration.'], ['Immersion evaluation', 'Compare workload, hardware compatibility and maintenance requirements before selection.'], ['Thermal monitoring', 'Align telemetry, leak detection and alarms with facility operating procedures.']];
export default async function ContentPage({ params }: {
    params: Promise<{
        slug: string;
    }>;
}) {
    const { slug } = await params;
    const page = pages[slug as PageSlug];
    if (!page)
        notFound();
    return <><section className="page-hero container"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="hero-description">{page.description}</p><div className="actions"><Button href={`/contact?intent=${slug === 'technology-partners' ? 'partner' : slug === 'robotics' ? 'audit' : 'quote'}`}>{slug === 'technology-partners' ? 'Become a Technology Partner' : slug === 'robotics' ? 'Start a Robotics Audit' : 'Discuss your project'}</Button><Button secondary href="/contact?intent=demo">Book a Demo</Button></div></section>
    {slug === 'robotics' && <><section className="section container"><SectionHeading label="CATALOG FOUNDATION" title="Choose the task. Then the platform." text="Capability categories for solution discovery. Specific models, manufacturers and availability are confirmed during project scoping."/><div className="detail-grid">{categories.map(c => <Link className="detail-card" key={c.slug} href={`/robotics/${c.slug}`}><p className="eyebrow">{c.tag}</p><h2>{c.name}</h2><p>{c.description}</p><span className="text-link">Explore use cases ↗</span></Link>)}</div></section><Commercial /><Process /></>}
    {slug === 'liquid-cooling' && <><div className="container cooling-feature"><InfraVisual compact/><div><p className="eyebrow">THERMAL DESIGN AS A SYSTEM</p><h2>More than a cooling component.</h2><p className="muted">Evaluate the complete heat path—from compute to facility rejection. System selection depends on workload, existing infrastructure and operating constraints.</p></div></div><section className="section container"><div className="detail-grid">{cooling.map(([title, text]) => <article className="detail-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><p className="disclaimer">Final thermal performance, capacity and efficiency depend on engineered system design and validated site conditions.</p></section><section className="section container"><SectionHeading label="BEYOND THERMAL MANAGEMENT" title="Connect the facility." text="Combine cooling telemetry with inspection robotics and AI-assisted monitoring."/><Button secondary href="/autonomous-data-center-operations">Autonomous Data Center Operations</Button></section></>}
    {slug === 'industries' && <section className="section container"><div className="detail-grid">{industries.map(([title, text], i) => <article className="detail-card" key={title}><p className="eyebrow">SECTOR / 0{i + 1}</p><h2>{title}</h2><p>{text}</p><Link href={`/contact?intent=audit&industry=${encodeURIComponent(title)}`} className="text-link">Discuss this environment ↗</Link></article>)}</div></section>}
    {slug === 'raas' && <><Commercial /><section className="section container"><SectionHeading label="DEFINE THE SERVICE BEFORE THE SUBSCRIPTION" title="A clear operating agreement."/><div className="detail-grid">{[['Scope & baseline', 'Define the task, site coverage and current operating baseline.'], ['Deployment & acceptance', 'Agree site readiness, integration, validation and acceptance criteria.'], ['Service measures', 'Set availability, task completion and escalation measures appropriate to the workflow.'], ['Responsibilities & lifecycle', 'Clarify operators, support, maintenance, data handling and end-of-term arrangements.']].map(([title, text]) => <article className="detail-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><p className="disclaimer">RaaS terms are project-specific. No guaranteed outcome, fixed price or universal service availability is implied.</p></section></>}
    {slug === 'technology-partners' && <section className="section container"><SectionHeading label="AN OPEN CAPABILITY ECOSYSTEM" title="Complementary expertise. Shared standards." text="This is a capability map and invitation to collaborate. No manufacturer is presented as an official partner, dealer or represented brand."/><div className="detail-grid">{[['Robotics platforms', 'Humanoid, mobile, manipulation and service platforms.'], ['Thermal infrastructure', 'Cooling distribution, cold plates, immersion and facility integration.'], ['Sensing & connectivity', 'Industrial telemetry, inspection sensors and secure communications.'], ['Software & integration', 'Fleet orchestration, AI monitoring and digital twin interfaces.']].map(([title, text]) => <article className="detail-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><p className="disclaimer">Any commercial relationship, territory rights, warranty and product availability must be confirmed through a written agreement.</p></section>}
    {slug === 'company' && <><section className="section container"><SectionHeading label="OUR APPROACH" title="Start with the operation." text="Technology earns its place by fitting the environment and solving a defined problem. Our approach is to connect infrastructure planning with practical automation, transparent scoping and a clear path to validation."/><div className="detail-grid">{[['Engineering-led', 'Assess interfaces, safety and maintainability before specifying equipment.'], ['Commercially flexible', 'Evaluate ownership, leasing, rental and service models against the project.'], ['Operationally grounded', 'Define people, processes and support alongside the technology.'], ['Transparent by design', 'Confirm availability and commercial relationships; avoid unsupported claims.']].map(([title, text]) => <article className="detail-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div></section><Process /></>}
    {slug === 'autonomous-data-center-operations' && <><section className="section container"><InfraVisual compact/><p className="disclaimer">Conceptual reference architecture. Integration, autonomous actions and performance require site-specific engineering and validation.</p></section><section className="section container"><div className="detail-grid">{[['01 / Thermal foundation', 'Liquid cooling telemetry provides temperature, flow and system status context.'], ['02 / Operational sensing', 'Fixed sensors and inspection robots capture facility conditions and asset observations.'], ['03 / AI-assisted monitoring', 'Combine signals to support anomaly review and operator prioritization.'], ['04 / Digital twin & oversight', 'Map signals to assets and workflows. Keep critical actions behind defined approval and safety controls.']].map(([title, text]) => <article className="detail-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div></section></>}
    <CTA /></>;
}
function Commercial() { return <section className="section container"><SectionHeading label="COMMERCIAL MODELS" title="Buy. Lease. Rent. RaaS."/><div className="model-grid">{models.map(([name, title, text]) => <article className="model-card" key={name}><h3>{name}</h3><h4>{title}</h4><p>{text}</p><Link className="text-link" href={`/contact?intent=quote&model=${name}`}>Request a Quote ↗</Link></article>)}</div></section>; }
function Process() { return <section className="section container"><SectionHeading label="FROM QUESTION TO QUALIFIED PROJECT" title="A practical path to deployment."/><ol className="process"><li><b>01 / Discover</b><p>Capture the task, constraints and success criteria.</p></li><li><b>02 / Validate</b><p>Assess site readiness, risk and technical fit.</p></li><li><b>03 / Pilot</b><p>Agree a controlled trial and acceptance measures.</p></li><li><b>04 / Scale</b><p>Plan integration, training and lifecycle support.</p></li></ol></section>; }
